spring:
  application:
    name: Eureka-Server

server:
  port: 1112

# 作为服务中心配置，并将serviceUrl指向peer1
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/


